ALTER TABLE users
    ADD COLUMN
IF NOT EXISTS first_name VARCHAR
(50),
ADD COLUMN
IF NOT EXISTS last_name VARCHAR
(50),
ADD COLUMN
IF NOT EXISTS status VARCHAR
(16) NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN
IF NOT EXISTS faculty_id BIGINT,
ADD COLUMN
IF NOT EXISTS major_id BIGINT;

ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_faculty;
ALTER TABLE users ADD CONSTRAINT fk_users_faculty
    FOREIGN KEY (faculty_id) REFERENCES faculties(id) ON DELETE SET NULL;

ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_major;
ALTER TABLE users ADD CONSTRAINT fk_users_major
    FOREIGN KEY (major_id) REFERENCES majors(id) ON DELETE SET NULL;


