-- Add missing elective column to knowledge_blocks table
-- This column was expected by the KnowledgeBlock entity but missing from the database
ALTER TABLE knowledge_blocks ADD COLUMN
IF NOT EXISTS elective BOOLEAN NOT NULL DEFAULT FALSE;

-- Create frame_clones table for tracking frame cloning operations
CREATE TABLE
IF NOT EXISTS frame_clones
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_major_id BIGINT,
    target_major_id BIGINT,
    created_by BIGINT,
    cloned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_frame_clones_source_major FOREIGN KEY
(source_major_id) REFERENCES majors
(id) ON
DELETE
SET NULL
,
    CONSTRAINT fk_frame_clones_target_major FOREIGN KEY
(target_major_id) REFERENCES majors
(id) ON
DELETE
SET NULL
,
    CONSTRAINT fk_frame_clones_created_by FOREIGN KEY
(created_by) REFERENCES users
(id) ON
DELETE
SET NULL
);

-- Add indexes for better performance
CREATE INDEX
IF NOT EXISTS idx_frame_clones_source_major ON frame_clones
(source_major_id);
CREATE INDEX
IF NOT EXISTS idx_frame_clones_target_major ON frame_clones
(target_major_id);
CREATE INDEX
IF NOT EXISTS idx_frame_clones_created_by ON frame_clones
(created_by);
CREATE INDEX
IF NOT EXISTS idx_frame_clones_cloned_at ON frame_clones
(cloned_at);
