package com.example.myapp.migration;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.Map;

@RestController
@RequestMapping("/api/migration")
@CrossOrigin(origins = "*")
public class MigrationController {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @PostMapping("/fix-schema")
    public ResponseEntity<Map<String, String>> fixSchema() {
        Map<String, String> result = new HashMap<>();
        
        try {
            // Check if elective column exists
            String checkColumn = "SELECT column_name FROM information_schema.columns WHERE table_name = 'knowledge_blocks' AND column_name = 'elective'";
            var columnResult = jdbcTemplate.queryForList(checkColumn);
            
            if (columnResult.isEmpty()) {
                jdbcTemplate.execute("ALTER TABLE knowledge_blocks ADD COLUMN elective BOOLEAN NOT NULL DEFAULT FALSE");
                result.put("elective_column", "Added successfully");
            } else {
                result.put("elective_column", "Already exists");
            }
            
            // Check if frame_clones table exists
            String checkTable = "SELECT table_name FROM information_schema.tables WHERE table_name = 'frame_clones'";
            var tableResult = jdbcTemplate.queryForList(checkTable);
            
            if (tableResult.isEmpty()) {
                jdbcTemplate.execute("""
                    CREATE TABLE frame_clones (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        source_major_id BIGINT,
                        target_major_id BIGINT,
                        created_by BIGINT,
                        cloned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_frame_clones_source_major FOREIGN KEY (source_major_id) REFERENCES majors(id) ON DELETE SET NULL,
                        CONSTRAINT fk_frame_clones_target_major FOREIGN KEY (target_major_id) REFERENCES majors(id) ON DELETE SET NULL,
                        CONSTRAINT fk_frame_clones_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
                    )
                    """);
                
                // Add indexes
                jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_frame_clones_source_major ON frame_clones(source_major_id)");
                jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_frame_clones_target_major ON frame_clones(target_major_id)");
                jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_frame_clones_created_by ON frame_clones(created_by)");
                jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_frame_clones_cloned_at ON frame_clones(cloned_at)");
                
                result.put("frame_clones_table", "Created successfully");
            } else {
                result.put("frame_clones_table", "Already exists");
            }
            
            result.put("status", "success");
            return ResponseEntity.ok(result);
            
        } catch (Exception e) {
            result.put("status", "error");
            result.put("message", e.getMessage());
            return ResponseEntity.status(500).body(result);
        }
    }
}
